// SPDX-License-Identifier: MIT
/*
 * Youniversal - color system.
 *
 * The three palettes below are generated by `tools/palette_lab.py`, which derives
 * every role from a tonal ramp (CIE L*a*b*, D65) the way Material You does, then
 * asserts WCAG 2.1 contrast of at least 4.5:1 for every text/surface pairing
 * Youniversal ships. Regenerate with:
 *
 *     python3 tools/palette_lab.py
 */

package dev.youniversal.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

public fun youniversalLightColorScheme(): ColorScheme =
    lightColorScheme(
        primary = Color(0xFF2455CC),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE1E0FF),
        onPrimaryContainer = Color(0xFF00184A),
        inversePrimary = Color(0xFFC1C1FE),
        secondary = Color(0xFF585C7D),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDFE0FE),
        onSecondaryContainer = Color(0xFF131A35),
        tertiary = Color(0xFF066A60),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF82F6E6),
        onTertiaryContainer = Color(0xFF00201C),
        background = Color(0xFFF9F9FD),
        onBackground = Color(0xFF1B1B1E),
        surface = Color(0xFFF9F9FD),
        onSurface = Color(0xFF1B1B1E),
        surfaceVariant = Color(0xFFE1E2EA),
        onSurfaceVariant = Color(0xFF46464D),
        surfaceTint = Color(0xFF2455CC),
        inverseSurface = Color(0xFF303033),
        inverseOnSurface = Color(0xFFF0F0F4),
        error = Color(0xFFBD0E19),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD4),
        onErrorContainer = Color(0xFF3B0900),
        outline = Color(0xFF76767E),
        outlineVariant = Color(0xFFC5C6CE),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF9F9FD),
        surfaceDim = Color(0xFFD9DADD),
        surfaceContainer = Color(0xFFEDEDF1),
        surfaceContainerHigh = Color(0xFFE8E8EC),
        surfaceContainerHighest = Color(0xFFE2E2E6),
        surfaceContainerLow = Color(0xFFF3F3F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        primaryFixed = Color(0xFFE1E0FF),
        primaryFixedDim = Color(0xFFC1C1FE),
        onPrimaryFixed = Color(0xFF00184A),
        onPrimaryFixedVariant = Color(0xFF013FA4),
        secondaryFixed = Color(0xFFDFE0FE),
        secondaryFixedDim = Color(0xFFC1C4E9),
        onSecondaryFixed = Color(0xFF131A35),
        onSecondaryFixedVariant = Color(0xFF404564),
        tertiaryFixed = Color(0xFF82F6E6),
        tertiaryFixedDim = Color(0xFF64D9C9),
        onTertiaryFixed = Color(0xFF00201C),
        onTertiaryFixedVariant = Color(0xFF015048),
    )

public fun youniversalDarkColorScheme(): ColorScheme =
    darkColorScheme(
        primary = Color(0xFFC1C1FE),
        onPrimary = Color(0xFF002B75),
        primaryContainer = Color(0xFF013FA4),
        onPrimaryContainer = Color(0xFFE1E0FF),
        inversePrimary = Color(0xFF2455CC),
        secondary = Color(0xFFC1C4E9),
        onSecondary = Color(0xFF292F4C),
        secondaryContainer = Color(0xFF404564),
        onSecondaryContainer = Color(0xFFDFE0FE),
        tertiary = Color(0xFF64D9C9),
        onTertiary = Color(0xFF003732),
        tertiaryContainer = Color(0xFF015048),
        onTertiaryContainer = Color(0xFF82F6E6),
        background = Color(0xFF131316),
        onBackground = Color(0xFFE2E2E6),
        surface = Color(0xFF131316),
        onSurface = Color(0xFFE2E2E6),
        surfaceVariant = Color(0xFF46464D),
        onSurfaceVariant = Color(0xFFC5C6CE),
        surfaceTint = Color(0xFFC1C1FE),
        inverseSurface = Color(0xFFE2E2E6),
        inverseOnSurface = Color(0xFF303033),
        error = Color(0xFFFEB4A7),
        onError = Color(0xFF690002),
        errorContainer = Color(0xFF94000D),
        onErrorContainer = Color(0xFFFFDAD4),
        outline = Color(0xFF909098),
        outlineVariant = Color(0xFF46464D),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF39393C),
        surfaceDim = Color(0xFF131316),
        surfaceContainer = Color(0xFF1F1F22),
        surfaceContainerHigh = Color(0xFF292A2C),
        surfaceContainerHighest = Color(0xFF343437),
        surfaceContainerLow = Color(0xFF1B1B1E),
        surfaceContainerLowest = Color(0xFF0E0E11),
        primaryFixed = Color(0xFFE1E0FF),
        primaryFixedDim = Color(0xFFC1C1FE),
        onPrimaryFixed = Color(0xFF00184A),
        onPrimaryFixedVariant = Color(0xFF013FA4),
        secondaryFixed = Color(0xFFDFE0FE),
        secondaryFixedDim = Color(0xFFC1C4E9),
        onSecondaryFixed = Color(0xFF131A35),
        onSecondaryFixedVariant = Color(0xFF404564),
        tertiaryFixed = Color(0xFF82F6E6),
        tertiaryFixedDim = Color(0xFF64D9C9),
        onTertiaryFixed = Color(0xFF00201C),
        onTertiaryFixedVariant = Color(0xFF015048),
    )

public fun youniversalCreamColorScheme(): ColorScheme =
    lightColorScheme(
        primary = Color(0xFF984723),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDBCC),
        onPrimaryContainer = Color(0xFF321200),
        inversePrimary = Color(0xFFFEB697),
        secondary = Color(0xFF685C51),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEEE0D2),
        onSecondaryContainer = Color(0xFF231A0F),
        tertiary = Color(0xFF576418),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFDFE997),
        onTertiaryContainer = Color(0xFF1B1D00),
        background = Color(0xFFE2D5C7),
        onBackground = Color(0xFF261E13),
        surface = Color(0xFFE8DBCC),
        onSurface = Color(0xFF261E13),
        surfaceVariant = Color(0xFFE6D4C0),
        onSurfaceVariant = Color(0xFF4D402F),
        surfaceTint = Color(0xFF984723),
        inverseSurface = Color(0xFF3C3328),
        inverseOnSurface = Color(0xFFF9ECDD),
        error = Color(0xFFBD0E19),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD4),
        onErrorContainer = Color(0xFF3B0900),
        outline = Color(0xFF776856),
        outlineVariant = Color(0xFFCAB9A5),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF9ECDD),
        surfaceDim = Color(0xFFC6BAAB),
        surfaceContainer = Color(0xFFE8DBCC),
        surfaceContainerHigh = Color(0xFFDCD0C1),
        surfaceContainerHighest = Color(0xFFD1C5B6),
        surfaceContainerLow = Color(0xFFEDE0D2),
        surfaceContainerLowest = Color(0xFFF6E9DA),
        primaryFixed = Color(0xFFFFDBCC),
        primaryFixedDim = Color(0xFFFEB697),
        onPrimaryFixed = Color(0xFF321200),
        onPrimaryFixedVariant = Color(0xFF7B2E0C),
        secondaryFixed = Color(0xFFEEE0D2),
        secondaryFixedDim = Color(0xFFD2C4B7),
        onSecondaryFixed = Color(0xFF231A0F),
        onSecondaryFixedVariant = Color(0xFF50453A),
        tertiaryFixed = Color(0xFFDFE997),
        tertiaryFixedDim = Color(0xFFC3CD7C),
        onTertiaryFixed = Color(0xFF1B1D00),
        onTertiaryFixedVariant = Color(0xFF3F4C00),
    )
/** The Youniversal [ColorScheme] for [style], resolved against the system dark mode. */
public fun youniversalColorScheme(
    style: YouniversalBackgroundStyle,
    isSystemInDarkTheme: Boolean = false,
): ColorScheme = when (style.resolve(isSystemInDarkTheme)) {
    YouniversalBackgroundStyle.Light -> youniversalLightColorScheme()
    YouniversalBackgroundStyle.Dark -> youniversalDarkColorScheme()
    YouniversalBackgroundStyle.Cream -> youniversalCreamColorScheme()
    YouniversalBackgroundStyle.Auto -> youniversalLightColorScheme()
}

/**
 * Raises a scheme to Youniversal high contrast: deeper foreground colors, a stronger
 * outline and flat (untinted) containers so boundaries stay legible in bright light.
 */
public fun ColorScheme.youniversalHighContrast(isDark: Boolean): ColorScheme =
    if (isDark) {
        copy(
            onBackground = Color.White,
            onSurface = Color.White,
            onSurfaceVariant = onSurfaceVariant.youniversalLighten(0.22f),
            outline = outline.youniversalLighten(0.28f),
            outlineVariant = outlineVariant.youniversalLighten(0.16f),
            surfaceVariant = surfaceVariant.youniversalDarken(0.25f),
            surfaceContainer = surfaceContainer.youniversalDarken(0.35f),
            surfaceContainerHigh = surfaceContainerHigh.youniversalDarken(0.35f),
            surfaceContainerHighest = surfaceContainerHighest.youniversalDarken(0.35f),
        )
    } else {
        copy(
            onBackground = Color.Black,
            onSurface = Color.Black,
            onSurfaceVariant = onSurfaceVariant.youniversalDarken(0.22f),
            outline = outline.youniversalDarken(0.30f),
            outlineVariant = outlineVariant.youniversalDarken(0.18f),
            surfaceVariant = surfaceVariant.youniversalLighten(0.20f),
            surfaceContainer = surfaceContainer.youniversalLighten(0.30f),
            surfaceContainerHigh = surfaceContainerHigh.youniversalLighten(0.30f),
            surfaceContainerHighest = surfaceContainerHighest.youniversalLighten(0.30f),
        )
    }

/**
 * Keeps the Material You accent roles but swaps in the Cream neutral ramp, so a
 * wallpaper-derived palette still sits on aged paper.
 */
public fun ColorScheme.withCreamNeutrals(cream: ColorScheme = youniversalCreamColorScheme()): ColorScheme =
    copy(
        background = cream.background,
        onBackground = cream.onBackground,
        surface = cream.surface,
        onSurface = cream.onSurface,
        surfaceVariant = cream.surfaceVariant,
        onSurfaceVariant = cream.onSurfaceVariant,
        surfaceBright = cream.surfaceBright,
        surfaceDim = cream.surfaceDim,
        surfaceContainer = cream.surfaceContainer,
        surfaceContainerHigh = cream.surfaceContainerHigh,
        surfaceContainerHighest = cream.surfaceContainerHighest,
        surfaceContainerLow = cream.surfaceContainerLow,
        surfaceContainerLowest = cream.surfaceContainerLowest,
        inverseSurface = cream.inverseSurface,
        inverseOnSurface = cream.inverseOnSurface,
        outline = cream.outline,
        outlineVariant = cream.outlineVariant,
    )
